### ISSUE TITLE
关于论文中的Appendix丢失的问题

### ISSUE THREAD

**Issue by xin-fight** [JiahaoChen1/Calibration#1]
作者你好，非常感谢你的贡献。阅读论文后受益良多。
不过对于其中的一些证明和流程，论文中提到详细信息都写在Appendix中，但是我在下载的论文中并没有找到相关的Appendix，请问作者可以更新一下么？

**Comment by JiahaoChen1** [comment]
Thanks for your interest.
Our appendix: https://openaccess.thecvf.com/content/CVPR2023/supplemental/Chen_Transfer_Knowledge_From_CVPR_2023_supplemental.pdf

**Comment by xin-fight** [comment]
再次感谢作者的贡献
